# Generated by Django 2.2.5 on 2019-09-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('audio', models.URLField(max_length=220)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
